swagger: "2.0"
info:
  title: Overcooked API
  description: The API for the Overcooked Project
  version: 1.0.0

host: overcooked.nikeshnazareth.com
schemes:
  - https

paths: 'api/paths.yaml'
recipes: 'api/recipes.yaml'
food: 'api/food.yaml'
definitions: 'api/definitions.yaml'
errors: 'api/errors.yaml'