swagger: "2.0"
info:
  title: Overcooked API
  description: The API for the Overcooked Project
  version: 1.0.0

host: overcooked.2brothers.tech
schemes:
  - https

paths: 'api/paths.yaml'
cms: 'api/cms.yaml'
recipes: 'api/recipes.yaml'
food: 'api/food.yaml'
auth: 'api/auth.yaml'
definitions: 'api/definitions.yaml'
errors: 'api/errors.yaml'
upload: 'api/upload.yaml'
