swagger: "2.0"
info:
  title: Seed API
  description: The API for the Express Seed project
  version: 1.0.0

host: localhost:3000
schemes:
  - http

paths: 'api/dummy-path.yaml'
definitions: 'api/definitions.yaml'
responses: 'api/responses.yaml'